### ISSUE TITLE
Unknown command: version in vuepress

### ISSUE THREAD

**Issue by jeevan15498** [appcelerator/docs-devkit#22]
Hello

I am using vuepress `Versioning` Plugin. like this way

Install plugin in the vuepress project folder `project/`
```
npm i -D vuepress-plugin-versioning
```
And then modify `project/.vuepress/config.js` file
```
// project/.vuepress/config.js
module.exports = {
  plugins: ['versioning']
}
```
When I run this command. Showing error
```
vuepress version docs 1.0.0
```

```
Unknown command: version docs 1.0.0

tip Did you miss to specify the target docs dir? e.g. vuepress version [targetDir].
tip A custom command registered by a plugin requires VuePress to locate your site configuration like vuepress dev or vuepress build.
```
Project Structure
```
└─ project
   ├─ .vuepress
   |  └─ config.js
   ├─ node_modules
   ├─ pages
     └─ README.md
```
   

Environment Info:

  System:
    OS: Windows 8.1 6.3.9600
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found

**Comment by janvennemann** [comment]
Please take a look at the [Versioning guide](https://titanium-docs-devkit.netlify.com/guide/versioning.html) again. It is recommended to have all your docs in a subfolder called `docs` and the command you used expects this structure. Take a look at the [docs](https://github.com/appcelerator/docs-devkit/tree/develop/packages/docs) package in this repo for an example.

For you project it should be something like this:

```
project
├── docs
│   ├── .vuepress
|   |   └── config.js
│   └── README.md
├── node_modules
├── pages
│   └── README.md
└── package.json
```

**Comment by jeevan15498** [comment]
I am using this structure dir but error is still.  This is my project folder. Please check .

```
Unknown command: version docs 1.0.0
```

[demo.zip](https://github.com/appcelerator/docs-devkit/files/3956090/demo.zip)

**Comment by nmeri17** [comment]
@jeevan15498 why is the issue closed? Can you still recall how it was resolved?
