### ISSUE TITLE
Can the Versioning plugin support multiple sets of versions?

### ISSUE THREAD

**Issue by davidplatt** [appcelerator/docs-devkit#42]
I'd like to use the versioning plugin for product documentation, but have one VuePress site. Is this possible? For example:

_example.com/**product_a**/[version]/overview
example.com/**product_b**/[version]/overview_

Products A and B are on separate versions and I'd like to keep them that way, so when you navigate to example.com/product_a you see the current docs for product_a and options for any previous versions and when you go to example.com/product_b you see product_b and any previous versions.

I know I can change the versionedSourceDir so I can have my structure as example.com/product/version, but I don't see a way to have it support multiple products unless we have two separate VuePress instances. Is this possible?

**Comment by janvennemann** [comment]
No, that's currently not possible. The versioning only works for the entire VuePress site. You cannot have separate versions that only apply to specific sub-directories.
